title: Wing Chun System
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.25
  rhythmicContrast: 0.25
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: WingChunSystem
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5340502
layout_spectrum: 0.00181
