name: WingChunSystem
favicon: null
layout_spectrum: 0.7540807011537254
typography_spectrum: 0.35326194297522306
title: Wing Chun System
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.26126613025553524
  lightness: 0.12051270552910864
  saturation: 0.9448154137935489
  rhythmicContrast: 0.5277231975924224
purpose: []
